# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: adbac4aa95d3dd2af01b0abfd7f6acb53179e19a6f0827d40df3f4ba4126a5fd6cf99d2e5125840850422e77edf5df72917d4ffff96896ad3be3f51062297a5d

test:
  secret_key_base: cd9c78c813f49312ebd3951d0d1f06db7ecf96da6b71f5b7fe94a960494a6883ea9352ecd0279fd07b72e1931f59be94754643f36c7faf35e38f925ae3d51930

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
